from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any

from psycopg import sql
from psycopg.rows import dict_row, tuple_row
from psycopg_pool import ConnectionPool

from app.core.database import prepare_postgres_connection
from app.core.integral_mix_supervisors import (
    Supervisor,
    SupervisorAssignment,
    SupervisorAssignmentSelection,
    SupervisorFields,
    SupervisorHandoffOperation,
    SupervisorHandoffStep,
    SupervisorRoutingCategory,
    SupervisorStore,
)

SUPERVISORS_TABLE_NAME = "integral_mix_supervisors"
ASSIGNMENTS_TABLE_NAME = "integral_mix_supervisor_assignments"
HANDOFFS_TABLE_NAME = "integral_mix_supervisor_handoffs"


class PostgresIntegralMixSupervisorStore(SupervisorStore):
    def __init__(self, pool: ConnectionPool, *, schema: str | None = None) -> None:
        self._pool = pool
        self._schema = schema

    def setup(self) -> None:
        supervisors_table = self._supervisors_table_identifier()
        assignments_table = self._assignments_table_identifier()
        handoffs_table = self._handoffs_table_identifier()
        with self._pool.connection() as connection:
            prepare_postgres_connection(connection, self._schema, create_schema=True)
            with connection.transaction():
                with connection.cursor(row_factory=tuple_row) as cursor:
                    cursor.execute(
                        sql.SQL(
                            """
                            CREATE TABLE IF NOT EXISTS {} (
                                supervisor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nocodb_record_id BIGINT,
                                name TEXT NOT NULL,
                                phone TEXT,
                                category TEXT NOT NULL,
                                region TEXT NOT NULL,
                                leads_received INTEGER NOT NULL DEFAULT 0
                                    CHECK (leads_received >= 0),
                                is_active BOOLEAN NOT NULL DEFAULT FALSE,
                                minimum_order TEXT,
                                source_created_at TIMESTAMPTZ,
                                source_updated_at TIMESTAMPTZ,
                                source_payload JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                                imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                last_assigned_at TIMESTAMPTZ
                            )
                            """
                        ).format(supervisors_table)
                    )
                    cursor.execute(
                        sql.SQL(
                            """
                            ALTER TABLE {}
                            ADD COLUMN IF NOT EXISTS supervisor_id
                            BIGINT GENERATED BY DEFAULT AS IDENTITY
                            """
                        ).format(supervisors_table)
                    )
                    cursor.execute(
                        """
                        SELECT constraint_row.conname, attribute_row.attname
                        FROM pg_constraint AS constraint_row
                        CROSS JOIN LATERAL unnest(constraint_row.conkey) AS key_row(attnum)
                        JOIN pg_attribute AS attribute_row
                          ON attribute_row.attrelid = constraint_row.conrelid
                         AND attribute_row.attnum = key_row.attnum
                        WHERE constraint_row.conrelid = to_regclass(%s)
                          AND constraint_row.contype = 'p'
                        ORDER BY attribute_row.attname
                        """,
                        (SUPERVISORS_TABLE_NAME,),
                    )
                    primary_key_rows = cursor.fetchall()
                    primary_key_columns = [row[1] for row in primary_key_rows]
                    if primary_key_columns != ["supervisor_id"]:
                        if primary_key_rows:
                            cursor.execute(
                                sql.SQL("ALTER TABLE {} DROP CONSTRAINT {}").format(
                                    supervisors_table,
                                    sql.Identifier(primary_key_rows[0][0]),
                                )
                            )
                        cursor.execute(
                            sql.SQL(
                                "ALTER TABLE {} ADD CONSTRAINT {} PRIMARY KEY (supervisor_id)"
                            ).format(
                                supervisors_table,
                                sql.Identifier(f"{SUPERVISORS_TABLE_NAME}_pkey"),
                            )
                        )
                    cursor.execute(
                        sql.SQL(
                            "CREATE UNIQUE INDEX IF NOT EXISTS {} ON {} (nocodb_record_id) "
                            "WHERE nocodb_record_id IS NOT NULL"
                        ).format(
                            sql.Identifier(f"{SUPERVISORS_TABLE_NAME}_nocodb_id_idx"),
                            supervisors_table,
                        )
                    )
                    cursor.execute(
                        sql.SQL(
                            "ALTER TABLE {} ADD COLUMN IF NOT EXISTS last_assigned_at TIMESTAMPTZ"
                        ).format(supervisors_table)
                    )
                    cursor.execute(
                        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {} (is_active, region)").format(
                            sql.Identifier(f"{SUPERVISORS_TABLE_NAME}_active_region_idx"),
                            supervisors_table,
                        )
                    )
                    cursor.execute(
                        sql.SQL(
                            """
                            CREATE TABLE IF NOT EXISTS {} (
                                request_key TEXT PRIMARY KEY,
                                supervisor_id BIGINT NOT NULL REFERENCES {} (supervisor_id),
                                lead_state CHAR(2) NOT NULL,
                                route_categories TEXT[] NOT NULL,
                                match_mode TEXT NOT NULL CHECK (
                                    match_mode IN ('region_and_category', 'region_only')
                                ),
                                assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                            )
                            """
                        ).format(assignments_table, supervisors_table)
                    )
                    cursor.execute(
                        sql.SQL(
                            """
                            CREATE TABLE IF NOT EXISTS {} (
                                request_key TEXT PRIMARY KEY REFERENCES {} (request_key)
                                    ON DELETE CASCADE,
                                deal_seq BIGINT NOT NULL,
                                lead_payload JSONB NOT NULL,
                                status TEXT NOT NULL DEFAULT 'pending' CHECK (
                                    status IN ('pending', 'processing', 'delivered')
                                ),
                                crm_receipt JSONB,
                                supervisor_message_receipt JSONB,
                                lead_message_receipt JSONB,
                                attempts INTEGER NOT NULL DEFAULT 0,
                                last_error_code TEXT,
                                next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                lease_expires_at TIMESTAMPTZ,
                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                            )
                            """
                        ).format(handoffs_table, assignments_table)
                    )
                    cursor.execute(
                        sql.SQL(
                            "CREATE INDEX IF NOT EXISTS {} ON {} "
                            "(status, next_attempt_at, created_at)"
                        ).format(
                            sql.Identifier(f"{HANDOFFS_TABLE_NAME}_pending_idx"),
                            handoffs_table,
                        )
                    )

    def list_supervisors(self) -> list[Supervisor]:
        with self._pool.connection() as connection:
            with connection.cursor(row_factory=dict_row) as cursor:
                cursor.execute(
                    sql.SQL(
                        "SELECT * FROM {} ORDER BY is_active DESC, name ASC, supervisor_id ASC"
                    ).format(self._supervisors_table_identifier())
                )
                rows = cursor.fetchall()
        return [_supervisor_from_row(row) for row in rows]

    def create_supervisor(self, fields: SupervisorFields) -> Supervisor:
        with (
            self._pool.connection() as connection,
            connection.cursor(row_factory=dict_row) as cursor,
        ):
            cursor.execute(
                sql.SQL(
                    """
                    INSERT INTO {} (
                        name, phone, category, region, leads_received, is_active, minimum_order
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                    RETURNING *
                    """
                ).format(self._supervisors_table_identifier()),
                _fields_values(fields),
            )
            row = cursor.fetchone()
        return _supervisor_from_row(row)

    def update_supervisor(
        self,
        supervisor_id: int,
        fields: SupervisorFields,
    ) -> Supervisor | None:
        with (
            self._pool.connection() as connection,
            connection.cursor(row_factory=dict_row) as cursor,
        ):
            cursor.execute(
                sql.SQL(
                    """
                    UPDATE {}
                    SET name = %s,
                        phone = %s,
                        category = %s,
                        region = %s,
                        leads_received = %s,
                        is_active = %s,
                        minimum_order = %s,
                        updated_at = CURRENT_TIMESTAMP
                    WHERE supervisor_id = %s
                    RETURNING *
                    """
                ).format(self._supervisors_table_identifier()),
                (*_fields_values(fields), supervisor_id),
            )
            row = cursor.fetchone()
        return _supervisor_from_row(row) if row else None

    def set_supervisor_active(
        self,
        supervisor_id: int,
        *,
        is_active: bool,
    ) -> Supervisor | None:
        with (
            self._pool.connection() as connection,
            connection.cursor(row_factory=dict_row) as cursor,
        ):
            cursor.execute(
                sql.SQL(
                    """
                    UPDATE {}
                    SET is_active = %s, updated_at = CURRENT_TIMESTAMP
                    WHERE supervisor_id = %s
                    RETURNING *
                    """
                ).format(self._supervisors_table_identifier()),
                (is_active, supervisor_id),
            )
            row = cursor.fetchone()
        return _supervisor_from_row(row) if row else None

    def claim_supervisor(
        self,
        *,
        request_key: str,
        lead_state: str,
        route_categories: tuple[SupervisorRoutingCategory, ...],
        deal_seq: int | None = None,
        handoff_payload: dict[str, Any] | None = None,
        selector: Callable[
            [Sequence[Supervisor], str, tuple[SupervisorRoutingCategory, ...]],
            SupervisorAssignmentSelection,
        ],
    ) -> SupervisorAssignment:
        supervisors_table = self._supervisors_table_identifier()
        assignments_table = self._assignments_table_identifier()
        handoffs_table = self._handoffs_table_identifier()
        with self._pool.connection() as connection:
            with connection.transaction():
                with connection.cursor(row_factory=dict_row) as cursor:
                    assignment = self._existing_assignment(cursor, request_key)
                    if assignment is not None:
                        self._ensure_handoff_operation(
                            cursor,
                            handoffs_table=handoffs_table,
                            request_key=request_key,
                            deal_seq=deal_seq,
                            handoff_payload=handoff_payload,
                        )
                        return assignment

                    cursor.execute(
                        sql.SQL(
                            "SELECT * FROM {} WHERE is_active ORDER BY supervisor_id FOR UPDATE"
                        ).format(supervisors_table)
                    )
                    locked_rows = cursor.fetchall()

                    # A second request with the same key waits on the row locks above. Recheck
                    # after acquiring them so the counter is incremented only once.
                    assignment = self._existing_assignment(cursor, request_key)
                    if assignment is not None:
                        self._ensure_handoff_operation(
                            cursor,
                            handoffs_table=handoffs_table,
                            request_key=request_key,
                            deal_seq=deal_seq,
                            handoff_payload=handoff_payload,
                        )
                        return assignment

                    supervisors = tuple(_supervisor_from_row(row) for row in locked_rows)
                    selection = selector(supervisors, lead_state, route_categories)
                    selected_row = next(
                        (
                            supervisor
                            for supervisor in supervisors
                            if supervisor.supervisor_id == selection.supervisor_id
                        ),
                        None,
                    )
                    if selected_row is None:
                        raise RuntimeError("The selected supervisor is not in the locked roster.")

                    cursor.execute(
                        sql.SQL(
                            """
                            UPDATE {}
                            SET leads_received = leads_received + 1,
                                last_assigned_at = CURRENT_TIMESTAMP,
                                updated_at = CURRENT_TIMESTAMP
                            WHERE supervisor_id = %s
                            RETURNING *
                            """
                        ).format(supervisors_table),
                        (selection.supervisor_id,),
                    )
                    updated_row = cursor.fetchone()
                    cursor.execute(
                        sql.SQL(
                            """
                            INSERT INTO {} (
                                request_key, supervisor_id, lead_state,
                                route_categories, match_mode
                            ) VALUES (%s, %s, %s, %s, %s)
                            """
                        ).format(assignments_table),
                        (
                            request_key,
                            selection.supervisor_id,
                            selection.lead_state,
                            list(selection.route_categories),
                            selection.match_mode,
                        ),
                    )
                    self._ensure_handoff_operation(
                        cursor,
                        handoffs_table=handoffs_table,
                        request_key=request_key,
                        deal_seq=deal_seq,
                        handoff_payload=handoff_payload,
                    )

        return SupervisorAssignment(
            supervisor=_supervisor_from_row(updated_row),
            lead_state=selection.lead_state,
            route_categories=selection.route_categories,
            match_mode=selection.match_mode,
        )

    def _ensure_handoff_operation(
        self,
        cursor: Any,
        *,
        handoffs_table: sql.Identifier,
        request_key: str,
        deal_seq: int | None,
        handoff_payload: dict[str, Any] | None,
    ) -> None:
        if deal_seq is None or handoff_payload is None:
            return
        from psycopg.types.json import Jsonb

        cursor.execute(
            sql.SQL(
                "INSERT INTO {} (request_key, deal_seq, lead_payload) "
                "VALUES (%s, %s, %s) ON CONFLICT (request_key) DO NOTHING"
            ).format(handoffs_table),
            (request_key, deal_seq, Jsonb(handoff_payload)),
        )

    def claim_pending_handoffs(
        self,
        *,
        request_key: str | None = None,
        limit: int = 20,
    ) -> list[SupervisorHandoffOperation]:
        if limit < 1:
            return []
        handoffs_table = self._handoffs_table_identifier()
        assignments_table = self._assignments_table_identifier()
        supervisors_table = self._supervisors_table_identifier()
        with self._pool.connection() as connection:
            with connection.transaction():
                with connection.cursor(row_factory=dict_row) as cursor:
                    cursor.execute(
                        sql.SQL(
                            """
                            WITH selected AS (
                                SELECT request_key FROM {}
                                WHERE status IN ('pending', 'processing')
                                  AND next_attempt_at <= CURRENT_TIMESTAMP
                                  AND (lease_expires_at IS NULL OR
                                       lease_expires_at < CURRENT_TIMESTAMP)
                                  AND (%s OR request_key = %s)
                                ORDER BY created_at, request_key
                                FOR UPDATE SKIP LOCKED
                                LIMIT %s
                            )
                            UPDATE {} AS operation
                            SET status = 'processing',
                                attempts = attempts + 1,
                                lease_expires_at = CURRENT_TIMESTAMP + INTERVAL '2 minutes',
                                updated_at = CURRENT_TIMESTAMP
                            FROM selected
                            WHERE operation.request_key = selected.request_key
                            RETURNING operation.request_key
                            """
                        ).format(handoffs_table, handoffs_table),
                        (request_key is None, request_key, limit),
                    )
                    claimed_keys = [row["request_key"] for row in cursor.fetchall()]
                    if not claimed_keys:
                        return []
                    cursor.execute(
                        sql.SQL(
                            """
                            SELECT operation.*, supervisor.*
                            FROM {} AS operation
                            JOIN {} AS assignment USING (request_key)
                            JOIN {} AS supervisor USING (supervisor_id)
                            WHERE operation.request_key = ANY(%s)
                            ORDER BY operation.created_at, operation.request_key
                            """
                        ).format(handoffs_table, assignments_table, supervisors_table),
                        (claimed_keys,),
                    )
                    rows = cursor.fetchall()
        return [_handoff_operation_from_row(row) for row in rows]

    def get_handoff_operation(
        self,
        *,
        request_key: str,
    ) -> SupervisorHandoffOperation | None:
        handoffs_table = self._handoffs_table_identifier()
        assignments_table = self._assignments_table_identifier()
        supervisors_table = self._supervisors_table_identifier()
        with (
            self._pool.connection() as connection,
            connection.cursor(row_factory=dict_row) as cursor,
        ):
            cursor.execute(
                sql.SQL(
                    "SELECT operation.*, supervisor.* FROM {} AS operation "
                    "JOIN {} AS assignment USING (request_key) "
                    "JOIN {} AS supervisor USING (supervisor_id) "
                    "WHERE operation.request_key = %s"
                ).format(handoffs_table, assignments_table, supervisors_table),
                (request_key,),
            )
            row = cursor.fetchone()
        return _handoff_operation_from_row(row) if row else None

    def mark_handoff_step(
        self,
        *,
        request_key: str,
        step: SupervisorHandoffStep,
        receipt: dict[str, Any],
    ) -> None:
        from psycopg.types.json import Jsonb

        receipt_column = {
            "crm_synced": "crm_receipt",
            "supervisor_notified": "supervisor_message_receipt",
            "lead_notified": "lead_message_receipt",
        }[step]
        handoffs_table = self._handoffs_table_identifier()
        with self._pool.connection() as connection:
            with connection.transaction():
                with connection.cursor() as cursor:
                    cursor.execute(
                        sql.SQL(
                            "UPDATE {} SET {} = %s, last_error_code = NULL, "
                            "next_attempt_at = CURRENT_TIMESTAMP, "
                            "updated_at = CURRENT_TIMESTAMP, status = 'processing' "
                            "WHERE request_key = %s"
                        ).format(handoffs_table, sql.Identifier(receipt_column)),
                        (Jsonb(receipt), request_key),
                    )
                    cursor.execute(
                        sql.SQL(
                            "UPDATE {} SET status = 'delivered', lease_expires_at = NULL, "
                            "updated_at = CURRENT_TIMESTAMP WHERE request_key = %s "
                            "AND crm_receipt IS NOT NULL "
                            "AND supervisor_message_receipt IS NOT NULL "
                            "AND lead_message_receipt IS NOT NULL"
                        ).format(handoffs_table),
                        (request_key,),
                    )

    def record_handoff_failure(self, *, request_key: str, error_code: str) -> None:
        handoffs_table = self._handoffs_table_identifier()
        with self._pool.connection() as connection, connection.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    "UPDATE {} SET status = 'pending', last_error_code = %s, "
                    "next_attempt_at = CURRENT_TIMESTAMP + "
                    "LEAST(POWER(2, LEAST(attempts, 8))::INTEGER, 300) * "
                    "INTERVAL '1 second', lease_expires_at = NULL, "
                    "updated_at = CURRENT_TIMESTAMP WHERE request_key = %s"
                ).format(handoffs_table),
                (error_code[:120], request_key),
            )

    def _existing_assignment(self, cursor: Any, request_key: str) -> SupervisorAssignment | None:
        cursor.execute(
            sql.SQL(
                """
                SELECT supervisor.*, assignment.lead_state AS assignment_lead_state,
                       assignment.route_categories AS assignment_route_categories,
                       assignment.match_mode AS assignment_match_mode
                FROM {} AS assignment
                JOIN {} AS supervisor USING (supervisor_id)
                WHERE assignment.request_key = %s
                """
            ).format(self._assignments_table_identifier(), self._supervisors_table_identifier()),
            (request_key,),
        )
        row = cursor.fetchone()
        if row is None:
            return None
        return SupervisorAssignment(
            supervisor=_supervisor_from_row(row),
            lead_state=row["assignment_lead_state"].strip(),
            route_categories=tuple(row["assignment_route_categories"]),
            match_mode=row["assignment_match_mode"],
            already_assigned=True,
        )

    def _supervisors_table_identifier(self) -> sql.Identifier:
        if self._schema:
            return sql.Identifier(self._schema, SUPERVISORS_TABLE_NAME)
        return sql.Identifier(SUPERVISORS_TABLE_NAME)

    def _assignments_table_identifier(self) -> sql.Identifier:
        if self._schema:
            return sql.Identifier(self._schema, ASSIGNMENTS_TABLE_NAME)
        return sql.Identifier(ASSIGNMENTS_TABLE_NAME)

    def _handoffs_table_identifier(self) -> sql.Identifier:
        if self._schema:
            return sql.Identifier(self._schema, HANDOFFS_TABLE_NAME)
        return sql.Identifier(HANDOFFS_TABLE_NAME)


def _fields_values(fields: SupervisorFields) -> tuple[Any, ...]:
    return (
        fields.name,
        fields.phone,
        fields.category,
        fields.region,
        fields.leads_received,
        fields.is_active,
        fields.minimum_order,
    )


def _supervisor_from_row(row: dict[str, Any]) -> Supervisor:
    return Supervisor(
        supervisor_id=int(row["supervisor_id"]),
        nocodb_record_id=(
            int(row["nocodb_record_id"]) if row.get("nocodb_record_id") is not None else None
        ),
        name=str(row["name"]),
        phone=row.get("phone"),
        category=str(row["category"]),
        region=str(row["region"]),
        leads_received=int(row["leads_received"]),
        is_active=bool(row["is_active"]),
        minimum_order=row.get("minimum_order"),
        last_assigned_at=row.get("last_assigned_at"),
        updated_at=row.get("updated_at"),
    )


def _handoff_operation_from_row(row: dict[str, Any]) -> SupervisorHandoffOperation:
    return SupervisorHandoffOperation(
        request_key=str(row["request_key"]),
        deal_seq=int(row["deal_seq"]),
        supervisor=_supervisor_from_row(row),
        lead_payload=dict(row["lead_payload"]),
        crm_synced=row.get("crm_receipt") is not None,
        supervisor_notified=row.get("supervisor_message_receipt") is not None,
        lead_notified=row.get("lead_message_receipt") is not None,
        attempts=int(row["attempts"]),
        last_error_code=row.get("last_error_code"),
    )
